
name: Build Angular App

on:
  push:
    branches: [ main, master ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.0' 

      - name: Install dependencies
        run: yarn install

      - name: Build Angular app
        run: npm build  

      - name: Deploy to build branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: build  
          folder: dist/test_build  # output folder
          clean: true
